<Project Sdk="Microsoft.NET.Sdk">

	<PropertyGroup>
		<GenerateAssemblyInfo>false</GenerateAssemblyInfo>
		<TargetFrameworks>net8.0;net9.0</TargetFrameworks>
		<AssemblyVersion>3.2.1.0</AssemblyVersion>
		<FileVersion>3.2.1.0</FileVersion>
		<Description>RavenDB job storage for Hangfire</Description>
		<PackageId>Job.Hangfire.Raven6x</PackageId>
		<Version>1.0.6</Version>
		<Authors>Kelvin Mateus Axhcar</Authors>
		<Company>KelvinAxhcar</Company>
		<Copyright>Copyright @ KelvinAxhcar</Copyright>
		<PackageLicenseExpression>LGPL-3.0-only</PackageLicenseExpression>
		<PackageReadmeFile>README.md</PackageReadmeFile>
		<PackageProjectUrl>https://github.com/kelvinaxhcar/Job-Hangfire-RavenDB</PackageProjectUrl>
		<PackageTags>Hangfire;AspNet;MVC;OWIN;RavenDB;Long-Running;Background;Fire-And-Forget;Delayed;Recurring;Tasks;Jobs;Scheduler;Threading;Queues</PackageTags>
		<RepositoryType>git</RepositoryType>
		<RepositoryUrl>https://github.com/kelvinaxhcar/Job-Hangfire-RavenDB</RepositoryUrl>
		<PublishRepositoryUrl>true</PublishRepositoryUrl>
		<EmbedUntrackedSources>true</EmbedUntrackedSources>
		<IncludeSymbols>true</IncludeSymbols>
		<SymbolPackageFormat>snupkg</SymbolPackageFormat>
		<ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
		<GeneratePackageOnBuild>true</GeneratePackageOnBuild>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Hangfire.AspNetCore" Version="1.8.15" />
		<PackageReference Include="Hangfire.Core" Version="1.8.15" />
		<PackageReference Include="Microsoft.Extensions.Caching.Memory" Version="8.0.1" />
		<PackageReference Include="Microsoft.SourceLink.GitHub" Version="8.0.0" PrivateAssets="All" />
		<PackageReference Include="Newtonsoft.Json" Version="13.0.3" />
		<PackageReference Include="RavenDB.Client" Version="6.2.0" />
		<None Include="..\..\README.md" Pack="true" PackagePath="\" />
		<EmbeddedResource Include="Resources\logo.png" />
	</ItemGroup>

	<ItemGroup>
	  <Compile Update="Resource.Designer.cs">
	    <DesignTime>True</DesignTime>
	    <AutoGen>True</AutoGen>
	    <DependentUpon>Resource.resx</DependentUpon>
	  </Compile>
	</ItemGroup>

	<ItemGroup>
	  <EmbeddedResource Update="Resource.resx">
	    <Generator>ResXFileCodeGenerator</Generator>
	    <LastGenOutput>Resource.Designer.cs</LastGenOutput>
	  </EmbeddedResource>
	</ItemGroup>

</Project>
